# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aece0a5e4afce96c28ea95d0aeaf8e3deb553b66765096eeec9d3291287cf3b0cf0e78ade45523c0cbe4e817314af8174d8efc4908510ba9affe1cc3b76dce37

test:
  secret_key_base: 352b14c1d13e4e0ff8685abb0467f8a66ae8cf7f1eb41a88ea533dd6460ff3f94a0b3e56543846464ac3de24fbb1d1a0b7d527af4c8081a551907b646a8a43df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
